name: timesheet
version: '1.3'
license: ISC
copyright: 2011-2019 Dino Morelli
author: Dino Morelli
maintainer: Dino Morelli <dino@ui3.info>
homepage: https://github.com/dino-/timesheet
synopsis: Add up timesheet values
description: Add up hours for days and weeks from a simple text file format.
category: Unknown
tested-with: GHC >= 8.6.5
extra-source-files:
- stack.yaml

github: dino-/timesheet

ghc-options:
- -fwarn-tabs
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

dependencies:
- base >= 4.8 && < 5.0

library:
  source-dirs: src/lib
  dependencies:
  - regex-compat

executables:
  timesheet:
    source-dirs: src/app
    main: Main.hs
    dependencies:
    - ansi-wl-pprint
    - heredoc
    - optparse-applicative
    - timesheet

tests:
  timesheet-test-suite:
    source-dirs: src/test
    main: Main.hs
    dependencies:
    - tasty
    - tasty-hunit
    - timesheet
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
